project:
  type: book

book:
  title: "Statistical Genetics"
  author: "Manuel Razo-Mejia"
  date: "8/3/2022"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - forces_evolution.qmd
      # - _bio_theory_phys.qmd
      # - _detereministic_evo.qmd
        # - _selection.qmd
        # - _mutation.qmd
      # - _randomness_life.qmd
        # - _buri_experiment.qmd
        # - _intro_langevin.qmd
        # - _stochastic_growth.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

number-depth: 3

format:
  html:
    theme: cosmo
    default-image-extension: png
  pdf:
    documentclass: scrreprt
    default-image-extension: pdf
    pdf-engine: pdflatex