project:
  type: book

book:
  title: "Statistical Genetics"
  author: "Manuel Razo-Mejia"
  date: "8/3/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - forces_evolution.qmd
      # - bio_theory_phys.qmd
      # - detereministic_evo.qmd
        # - selection.qmd
        # - mutation.qmd
      # - randomness_life.qmd
        # - buri_experiment.qmd
        # - intro_langevin.qmd
        # - stochastic_growth.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

number-depth: 3

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



