## Randomness of life

So far, we have studied two forces of evolution as deterministic. This idea of
having the same result every time the evolutionary dynamics are run sounds
paradoxical, given biologists' intuition about how the evolutionary process
works. On the one hand, any biologist will tell us that evolution is an entirely
random process; from the emergence of a beneficial mutation to fixing this
mutation in the population, these dynamics are extremely hard to predict. On the
other hand, in a conflicting view of evolution, biologists tend to associate
every biological feature with a product of selection. Either by natural or
sexual selection, the biology literature is full of "just-so-stories" that
attribute a functional purpose to every aspect of biological systems. Therefore,
the claim is that the process occurs randomly, but everything serves a purpose.
The truth most likely lies somewhere in between.

At the dawn of the modern synthesis of evolutionary theory Sewall Wright
concluded that reproductive stochasticity could play an important role in the
fate of populations. In other words, not because a beneficial mutation appeared
in the population, it would necessarily take over. Equivalently, a deleterious
mutation needs not to be immediately removed from the population. Accidents in
evolution still play an essential role when it comes to setting the fate of a
population. From losing a beneficial mutation due to non-selection-related
events such as the random death of the organism carrying the mutation to the
fixation of deleterious mutations. This stochasticity is especially important
when we think about small populations. The effects that the randomness of
reproduction and survival of organisms can have on the structure of a population
is the evolutionary force that we call *genetic drift*.


As we will see next, the first experimental demonstration of this
non-selection-based evolution came from Wright's academic lineage. His student,
Peter Buri designed the first experiment to demonstrate the force of genetic
drift.